---
beanstalkd_version: "1.10"
beanstalkd_listen_addr: "0.0.0.0"
beanstalkd_listen_port: "11300"
beanstalkd_user: "beanstalkd"
beanstalkd_enabled: "yes"


beanstalkd_persistent: Yes
beanstalkd_storage: "/var/lib/beanstalkd"
