---
  - name: Install nginx
    sudo: yes
    apt:  pkg=nginx state=latest

  - name: Ensure nginx log directory exists
    file: dest=/var/log/nginx/symfony state=directory

  - name: Change default nginx site
    sudo: yes
    template: src=default.tpl dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: Change controlpanel nginx config
    sudo: yes
    template: src=controlpanel.tpl dest=/etc/nginx/sites-available/controlpanel.conf
    # file: src=/etc/nginx/sites-available/controlpanel.conf dest=/etc/nginx/sites-enabled/controlpanel.conf
    # notify: restart nginx

  - name: Change controlpanel nginx config
    sudo: yes
    # template: src=controlpanel.tpl dest=/etc/nginx/sites-available/controlpanel.conf
    file: src=/etc/nginx/sites-available/controlpanel.conf dest=/etc/nginx/sites-enabled/controlpanel.conf state=link
    notify: restart nginx